version: '3.0'
services:
  drishti-haproxy:
    image: beapen/drishti-haproxy:latest
    ports:
      - "8080:8080"
    depends_on:
      - phis-dw

  phis-dw:
    image: beapen/fhir:latest
    env_file:
      - resource-server.env

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    env_file:
      - resource-server.env
    depends_on:
      - phis-dw

